### ISSUE TITLE
Show database error information 

### ISSUE THREAD

**Issue by SloNN** [ydb-platform/ydb-embedded-ui#1201] opened 2024-08-22 11:07 UTC
Make sure that error descriptions in JSON format for not 200 responses are displayed after https://github.com/ydb-platform/ydb/issues/8294

If database reports error while executing query, this information is not shown in UI. So they have to switch browser to developer mode to view error description

![telegram-cloud-photo-size-2-5301057290985659619-y](https://github.com/user-attachments/assets/46f29c3b-b132-4c18-b17b-efdd8b77ec97)

**Comment by adameat** [comment] 2024-08-22 12:54
can't reproduce neither on site nor embedded version (main)

**Comment by antonkovalenko** [comment] 2024-08-26 15:34
better diagnostics requires [#8294](https://github.com/ydb-platform/ydb/issues/8294)

**Comment by adameat** [comment] 2024-09-09 08:48
the problem was because of absence of compute nodes in serverless database. it was fixed by using shared database nodes.

**Closed by adameat** 2024-09-09 08:48 UTC
Labels: prio:high
